<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LotoApp.DataAccess\LotoApp.DataAccess.csproj" />
    <ProjectReference Include="..\LotoApp.DTOs\LotoApp.DTOs.csproj" />
  </ItemGroup>

</Project>
